### DISCUSSION TITLE
Style Snackbar Overlay

### DISCUSSION THREAD

**Discussion by ricardosaracino** [IgniteUI/igniteui-angular#10452] [Q&A]
## Question  
with the update from  v11 to v12 we lost the ability to set a max width on the snack bar

if i change the overlay styles it is applied globally and effects modals and toasts. Is there a way to achieve this in v12

![image](https://user-images.githubusercontent.com/759253/137410898-275faa27-e267-4164-b8cf-10aecaa1a692.png)

 * igniteui-angular version:  12
 * browser: chromium 

![image](https://user-images.githubusercontent.com/759253/137410752-ad5089e0-4e74-4df0-b8df-db853926082d.png)

```html
<igx-snackbar #snackbar (clicked)="snackbar.close()" [actionText]="'LABELS.CLOSE' | translate" class="warning-snackbar">
  <div *ngFor="let message of snackMessages" class="white-space-pre-wrap">{{ message }}</div>
</igx-snackbar>
```

```scss
@import '~@infragistics/igniteui-angular/lib/core/styles/themes/index';
@import '~styles/variables';

$snackbar-theme: igx-snackbar-theme(
  $text-color: black,
  $background: $warn,
  $button-color: black,
  $border-radius: 12px
);

@include igx-snackbar($snackbar-theme);

.warning-snackbar::ng-deep {

  flex: auto 1 1;
  min-width: 300px;

  .igx-snackbar__message {
    width: 100%;
    max-height: 120px;
    padding-right: 1.25em;
    overflow-y: auto;
    font-size: 1rem;
    font-weight: 600;
    line-height: 1.5;
  }

  .igx-snackbar__message::-webkit-scrollbar {
    width: 10px;
  }

  /* Track */
  .igx-snackbar__message::-webkit-scrollbar-track {
    border-radius: 5px;
    background-color: rgba(0, 0, 0, .1)
  }

  /* Handle todo this seems to not be working */
  .igx-snackbar__message::-webkit-scrollbar-thumb {
    background: black;
    border-radius: 10px;
  }

  /* Handle on hover */
  .igx-snackbar__message::-webkit-scrollbar-thumb:hover {
    background: black;
    border-radius: 10px;
  }
}
```
