### DISCUSSION TITLE
Create 2 themes for igx-dropdown and use them in the same App

### DISCUSSION THREAD

**Discussion by pmoleri** [IgniteUI/igniteui-angular#10732] [General]
Let's say I need 2 different themes for `igx-dropdown`. One with gray background and the other with white one.

I would do it like this:
```html
<igx-drop-down class="white">
    <igx-drop-down-item *ngFor="let item of items">
        {{ item.field }}
    </igx-drop-down-item>
</igx-drop-down>

<igx-drop-down class="gray">
    <igx-drop-down-item *ngFor="let item of items">
        {{ item.field }}
    </igx-drop-down-item>
</igx-drop-down>
```
```scss
@import '~igniteui-angular/lib/core/styles/themes/index';

$dropdown-white-theme: igx-dropdown-theme(
    $background-color : white;
);

$dropdown-gray-theme: igx-dropdown-theme(
    $background-color : gray;
);

::ng-deep igx-dropdown.white {
 @include igx-css-vars($dropdown-white-theme);
}

::ng-deep igx-dropdown.gray{
 @include igx-css-vars($dropdown-gray-theme);
}

```

The problem I have is that the classes don't propagate to the overlay, so I can't isolate the themes and they step over each other.

Is there some way to achieve this? Otherwise, I think all components that open in overlay should accept something like a `[overlayClass]` property, so we can easily set styles to a particular instance.
