### ISSUE TITLE
igx-input-group type="box" background changed

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#10483]
## Description  
The `igx-input-group` `type="box"` background changed in 13.0 from 12.2.

 * igniteui-angular version: 13.0.0-alpha.7
 * browser: all

## Steps to reproduce  

1. Create an angular view with an 
```html
<igx-input-group type="box">
  <label for="comment" igxLabel i18n>{{ !authUser ? 'Login to' : 'Leave a' }} comment...</label>
  <textarea [disabled]="!authUser" #commentBox id="comment" name="comment" igxInput [(ngModel)]="newComment.comment"></textarea>
  <button igxSuffix
		  igxButton="fab"
		  [ngClass]="strat.votes | hasVoted:1:authUser:pipeTrigger"
		  [disabled]="!newComment.comment">
	<igx-icon>send</igx-icon>
  </button>
</igx-input-group>
```
2. Use the following theme:
```scss
$primary: white !default;
$secondary: #FF0A3A !default;
$background: #192053;
$banner-background: #2C3D93;
$background-gradient: linear-gradient(to right, $background, #04081D);
$background-gradient-lighter: linear-gradient(135deg, #2f3978 0%, #10193f 100%);
$progress-success: #13FF21;

$app-palette: igx-palette($primary, $secondary);

@include igx-dark-theme(
  $palette: $app-palette
);

/* Input Group */
$input-group-theme: igx-input-group-theme($search-background: transparent,
                                          $idle-text-color: rgba(255, 255, 255, 0.75),
                                          $filled-text-color: white,
                                          $focused-text-color: white,
                                          $label-floated-background: $background);
@include igx-css-vars($input-group-theme);
/* END Input Group */

.igx-input-group__textarea,
textarea {
  resize: none;
  min-height: 128px;
}
```

## Result  
![image](https://user-images.githubusercontent.com/1472513/141307610-c9935cb8-664d-414c-bf19-f4cada8fe1ea.png)

## Expected result  
![image](https://user-images.githubusercontent.com/1472513/141307648-ab19d2fd-cf6e-425c-b06c-302705dfa341.png)

## Attachments  
Attach a sample if available, and screenshots, if applicable.
