### ISSUE TITLE
igx-chip has a different background color

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#10481]
## Description  
The `igx-chip` component looks different in 13.0 from 12.2. Note: to me the chip looks better, but if this is intentional, then it should be documented with an example of how to return its look and feel back to the old version.

 * igniteui-angular version: 13.0.0-alpha.7
 * browser: all

## Steps to reproduce  

1. Create an angular view with an `igx-chip`.
2. Define the following theme:
```scss
$primary: white !default;
$secondary: #FF0A3A !default;
$background: #192053;
$banner-background: #2C3D93;
$background-gradient: linear-gradient(to right, $background, #04081D);
$background-gradient-lighter: linear-gradient(135deg, #2f3978 0%, #10193f 100%);
$progress-success: #13FF21;

$app-palette: igx-palette($primary, $secondary);

@include igx-dark-theme(
  $palette: $app-palette
);

.igx-chip {
  margin: 4px 4px 4px 0;
}
```

## Result  
![image](https://user-images.githubusercontent.com/1472513/141305666-5e04be25-dbf4-4a72-aa2e-3eb05223f6a1.png)

Note: chips that are not selected are pretty much unreadable:
![image](https://user-images.githubusercontent.com/1472513/141317818-98e87ab2-2491-49d7-9b09-58727c52d8df.png)

## Expected result  
![image](https://user-images.githubusercontent.com/1472513/141305725-b6fb64f2-86da-4c1a-b7c5-466ca5e40589.png)

## Attachments  
Attach a sample if available, and screenshots, if applicable.
