### ISSUE TITLE
Sparkline chart - has many properties that don't work

### ISSUE THREAD

**Issue by desig9stein** [IgniteUI/igniteui-angular#11572]
## Description  
Most of the theme props don't seem to do anything.

 * igniteui-angular version: all
 * browser: all

```SCSS
$data-chart-theme: sparkline-theme(

 //Working props

    $brush: #07ea07,
    $negative-brush: orange,
    $line-thickness: 4px,
    

 //Not working props

    $marker-brush: red,
    $marker-size: 1px,
    $first-marker-brush: red,
    $first-marker-size: 1px,
    $last-marker-brush: red,
    $last-marker-size: 1px,
    $low-marker-brush: red,
    $low-marker-size: 1px,
    $high-marker-brush: red,
    $high-marker-size: 1px,
    $negative-marker-brush: red,
    $negative-marker-size: 1px,
    $trend-line-brush: red,
    $trend-line-thickness: 1px,
    $horizontal-axis-brush: red,
    $vertical-axis-brush: 1px,
    $normal-range-fill: red
);
```

Produced CSS vars
```SCSS
igx-sparkline {
    --brush: var(--sparkline-brush, #07ea07);
    --line-thickness: var(--sparkline-line-thickness, 4px);
    --marker-brush: var(--sparkline-marker-brush, red);

//Everything below have no effect on the chart.
    --marker-size: var(--sparkline-marker-size, 1px);
    --first-marker-brush: var(--sparkline-first-marker-brush, red);
    --first-marker-size: var(--sparkline-first-marker-size, 1px);
    --last-marker-brush: var(--sparkline-last-marker-brush, red);
    --last-marker-size: var(--sparkline-last-marker-size, 1px);
    --low-marker-brush: var(--sparkline-low-marker-brush, red);
    --low-marker-size: var(--sparkline-low-marker-size, 1px);
    --high-marker-brush: var(--sparkline-high-marker-brush, red);
    --high-marker-size: var(--sparkline-high-marker-size, 1px);
    --negative-brush: var(--sparkline-negative-brush, orange);
    --negative-marker-brush: var(--sparkline-negative-marker-brush, red);
    --negative-marker-size: var(--sparkline-negative-marker-size, 1px);
    --trend-line-brush: var(--sparkline-trend-line-brush, red);
    --trend-line-thickness: var(--sparkline-trend-line-thickness, 1px);
    --horizontal-axis-brush: var(--sparkline-horizontal-axis-brush, red);
    --vertical-axis-brush: var(--sparkline-vertical-axis-brush, 1px);
    --normal-range-fill: var(--sparkline-normal-range-fill, red);
}
```

if there is no custom theme, only --brush is produced as a CSS var.
