### ISSUE TITLE
Can't set border-radius in custom themes if base theme is set to roundness 0

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/igniteui-angular#11603]
## Description  
Can't set border-radius in custom themes if base theme is set to roundness 0

 * igniteui-angular version: 13.1.15
 * browser: all

## Steps to reproduce  

1. Configure base theme with roundness 0:
```scss
@include core();
@include typography();
@include theme($palette: $palette, $schema: $schema, $roundness: 0);
```

2. Create custom theme:
```scss
$custom-avatar-theme: avatar-theme(
  $color: green,
  $border-radius: 5px,
);

:host {
  @include css-vars($custom-avatar-theme);
}
```

## Result  
Custom border-radius is ignored.

## Attachments  
![image](https://user-images.githubusercontent.com/12942794/169615652-1f0b0fbf-86d4-4e64-8eca-41e5780b1314.png)
https://stackblitz.com/edit/angular-muzqcx?file=src%2Fapp%2Fbuttons-style%2Fbuttons-style.component.scss
