### ISSUE TITLE
Dockmanager theming not working

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#12384]
## Description  
Dockmanager theming isn't working anymore.
Since igniteui version 15 the styles for dockmanager are missing the prefix igc.

Version 14:

```css
igc-dockmanager {
    --igc-active-color: var(--igc-dockmanager-active-color, hsla(var(--igx-primary-500), var(--igx-primary-a)));
    --igc-background-color: var(--igc-dockmanager-background-color, hsla(var(--igx-grays-200), var(--igx-grays-a)));
    --igc-border-color: var(--igc-dockmanager-border-color, hsla(var(--igx-surface-500), var(--igx-surface-a)));
    --igc-button-text: var(--igc-dockmanager-button-text, hsla(var(--igx-grays-800), var(--igx-grays-a)));
    --igc-context-menu-color-active: var(--igc-dockmanager-context-menu-color-active, hsla(var(--igx-grays-800), var(--igx-grays-a)));
    --igc-dock-background: var(--igc-dockmanager-dock-background, hsla(var(--igx-grays-50), var(--igx-grays-a)));
    --igc-drop-shadow-background: var(--igc-dockmanager-drop-shadow-background, hsla(var(--igx-primary-900), .1));
    --igc-floating-pane-border-color: var(--igc-dockmanager-floating-pane-border-color, hsla(var(--igx-grays-400), var(--igx-grays-a)));
    --igc-flyout-shadow-color: var(--igc-dockmanager-flyout-shadow-color, hsla(var(--igx-grays-900), .1));
    --igc-joystick-border-color: var(--igc-dockmanager-joystick-border-color, hsla(var(--igx-grays-400), var(--igx-grays-a)));
    --igc-joystick-icon-color: var(--igc-dockmanager-joystick-icon-color, hsla(var(--igx-grays-800), var(--igx-grays-a)));
    --igc-joystick-icon-color-active: var(--igc-dockmanager-joystick-icon-color-active, hsla(var(--igx-grays-800), var(--igx-grays-a)));
    --igc-pane-content-background: var(--igc-dockmanager-pane-content-background, hsla(var(--igx-surface-500), var(--igx-surface-a)));
    --igc-pane-header-background: var(--igc-dockmanager-pane-header-background, hsla(var(--igx-grays-100), var(--igx-grays-a)));
    --igc-pinned-header-background: var(--igc-dockmanager-pinned-header-background, hsla(var(--igx-grays-50), var(--igx-grays-a)));
    --igc-splitter-background: var(--igc-dockmanager-splitter-background, hsla(var(--igx-grays-100), var(--igx-grays-a)));
    --igc-tab-background-active: var(--igc-dockmanager-tab-background-active, hsla(var(--igx-surface-500), var(--igx-surface-a)));
    --igc-text-color: var(--igc-dockmanager-text-color, hsla(var(--igx-grays-800), var(--igx-grays-a)));
    --igc-context-menu-background-active: var(--igc-dockmanager-context-menu-background-active, hsla(var(--igx-grays-200), var(--igx-grays-a)));
    --igc-context-menu-color: var(--igc-dockmanager-context-menu-color, hsla(var(--igx-grays-800), var(--igx-grays-a)));
    --igc-joystick-background-active: var(--igc-dockmanager-joystick-background-active, hsla(var(--igx-grays-200), var(--igx-grays-a)));
    --igc-splitter-handle: var(--igc-dockmanager-splitter-handle, hsla(var(--igx-grays-400), var(--igx-grays-a)));
    --igc-tab-background: var(--igc-dockmanager-tab-background, hsla(var(--igx-surface-500), var(--igx-surface-a)));
    --igc-tab-border-color-active: var(--igc-dockmanager-tab-border-color-active, hsla(var(--igx-surface-500), var(--igx-surface-a)));
    --igc-tab-border-color: var(--igc-dockmanager-tab-border-color, hsla(var(--igx-surface-500), var(--igx-surface-a)));
    --igc-tab-text-active: var(--igc-dockmanager-tab-text-active, hsla(var(--igx-primary-500), var(--igx-primary-a)));
    --igc-tab-text: var(--igc-dockmanager-tab-text, hsla(var(--igx-grays-700), var(--igx-grays-a)));
}
```

Version 15:

```css
igc-dockmanager {
    --active-color: var(--igc-dockmanager-active-color, hsla(var(--ig-primary-500), var(--ig-primary-a)));
    --background-color: var(--igc-dockmanager-background-color, hsla(var(--ig-gray-200), var(--ig-gray-a)));
    --border-color: var(--igc-dockmanager-border-color, hsla(var(--ig-surface-500), var(--ig-surface-a)));
    --button-text: var(--igc-dockmanager-button-text, hsla(var(--ig-gray-800), var(--ig-gray-a)));
    --context-menu-color-active: var(--igc-dockmanager-context-menu-color-active, hsla(var(--ig-gray-800), var(--ig-gray-a)));
    --dock-background: var(--igc-dockmanager-dock-background, hsla(var(--ig-gray-50), var(--ig-gray-a)));
    --drop-shadow-background: var(--igc-dockmanager-drop-shadow-background, hsla(var(--ig-primary-900), 0.1));
    --floating-pane-border-color: var(--igc-dockmanager-floating-pane-border-color, hsla(var(--ig-gray-400), var(--ig-gray-a)));
    --flyout-shadow-color: var(--igc-dockmanager-flyout-shadow-color, hsla(var(--ig-gray-900), 0.1));
    --joystick-border-color: var(--igc-dockmanager-joystick-border-color, hsla(var(--ig-gray-400), var(--ig-gray-a)));
    --joystick-icon-color: var(--igc-dockmanager-joystick-icon-color, hsla(var(--ig-gray-800), var(--ig-gray-a)));
    --joystick-icon-color-active: var(--igc-dockmanager-joystick-icon-color-active, hsla(var(--ig-gray-800), var(--ig-gray-a)));
    --pane-content-background: var(--igc-dockmanager-pane-content-background, hsla(var(--ig-surface-500), var(--ig-surface-a)));
    --pane-header-background: var(--igc-dockmanager-pane-header-background, hsla(var(--ig-gray-100), var(--ig-gray-a)));
    --pinned-header-background: var(--igc-dockmanager-pinned-header-background, hsla(var(--ig-gray-50), var(--ig-gray-a)));
    --splitter-background: var(--igc-dockmanager-splitter-background, hsla(var(--ig-gray-100), var(--ig-gray-a)));
    --tab-background-active: var(--igc-dockmanager-tab-background-active, hsla(var(--ig-surface-500), var(--ig-surface-a)));
    --text-color: var(--igc-dockmanager-text-color, hsla(var(--ig-gray-800), var(--ig-gray-a)));
    --context-menu-background-active: var(--igc-dockmanager-context-menu-background-active, hsla(var(--ig-gray-200), var(--ig-gray-a)));
    --context-menu-color: var(--igc-dockmanager-context-menu-color, hsla(var(--ig-gray-800), var(--ig-gray-a)));
    --joystick-background-active: var(--igc-dockmanager-joystick-background-active, hsla(var(--ig-gray-200), var(--ig-gray-a)));
    --splitter-handle: var(--igc-dockmanager-splitter-handle, hsla(var(--ig-gray-400), var(--ig-gray-a)));
    --tab-background: var(--igc-dockmanager-tab-background, hsla(var(--ig-surface-500), var(--ig-surface-a)));
    --tab-border-color-active: var(--igc-dockmanager-tab-border-color-active, hsla(var(--ig-surface-500), var(--ig-surface-a)));
    --tab-border-color: var(--igc-dockmanager-tab-border-color, hsla(var(--ig-surface-500), var(--ig-surface-a)));
    --tab-text-active: var(--igc-dockmanager-tab-text-active, hsla(var(--ig-primary-500), var(--ig-primary-a)));
    --tab-text: var(--igc-dockmanager-tab-text, hsla(var(--ig-gray-700), var(--ig-gray-a)));
}
```
