### ISSUE TITLE
Themes: font-size on ig-typography

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#12401]
## Description  
If you want to have a smaller font-size then you have to set the font-size on the html element like

```css
html {
  font-size: 14px;
}
```

But in the `ig-typography` class the font-size is set to 16px;

```css
.ig-typography {
    font-family: var(--ig-font-family);
    font-size: 16px;
    line-height: 1.6875rem;
}
```

Shouldn't the font-size be 1rem or not set at all?
Because now I have to set the font-size on `html` and `ig-typography`.
