### ISSUE TITLE
Textarea: wrong font-size

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#12854]
## Description  
The css for textarea has a fixed font-size of 16px.
This should be the same size as a normal input (.875rem)

https://stackblitz.com/edit/angular-jee4co

 * used theme: igniteui-fluent-light-word
 * igniteui-angular version: 15.1.0

```css
.ig-typography .igx-input-group__input,.ig-typography .igx-input-group__textarea {
    font-family: var(--ig-subtitle-1-font-family, var(--ig-font-family));
    font-size: var(--ig-subtitle-1-font-size);
    font-weight: var(--ig-subtitle-1-font-weight);
    font-style: var(--ig-subtitle-1-font-style);
    line-height: var(--ig-subtitle-1-line-height);
    letter-spacing: var(--ig-subtitle-1-letter-spacing);
    text-transform: var(--ig-subtitle-1-text-transform);
    margin-top: var(--ig-subtitle-1-margin-top);
    margin-bottom: var(--ig-subtitle-1-margin-bottom);
    font-size: 16px;
    margin: 0
}
```
