### ISSUE TITLE
avatar-theme doesn't build after update to 16

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#13017]
## Description  
Initialization code for `avatar-theme` now errors after an update to igniteui-angular `16.0.0`

 * igniteui-angular version: 16.0.0
 * browser: N/A

## Steps to reproduce  

1. I have the following code in my project:
```scss
  .empty-role {
    $empty-role-avatar: avatar-theme($color: #000, $size: 88px);
    @include css-vars($empty-role-avatar);
  }
```

## Result  
Build fails after an update to `16.0.0`

## Expected result  
Build should not fail, or my code should have been migrated.

## Attachments  
![image](https://github.com/IgniteUI/igniteui-angular/assets/1472513/c6fd0099-ce05-4dd5-901e-1437ea421bfb)
