### ISSUE TITLE
Select item built-in prefix/suffix support

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular#13208]
## Is your feature request related to a problem? Please describe.
Per the title - it would be beneficial both functionality and consistency wise if the select items support the same prefix and suffix projection their base dropdown item does.
Related to #8656 that did the same for the Dropdown items
Also the [Web Components Select item already has prefix/suffix](https://www.infragistics.com/products/ignite-ui-web-components/web-components/components/inputs/select#item) (again inherited from the dropdown item).

## Describe the solution you'd like
Would like similar internal structure as the dropdown item the select item inherits that has slots to project prefix/suffix. Ideally, after evaluation, it'd be nice if the current setup is altered in a way that won't affect any existing app usage and can be delivered as an enhancement.

## Describe alternatives you've considered
I guess we can do what the samples do, which is not pretty at all. The sample under header/footer section is clearly meant to be a suffix:
![image](https://github.com/IgniteUI/igniteui-angular/assets/3198469/41977690-e0fc-4624-96df-2189da129afa)
But it's done with CSS:
```scss
:host ::ng-deep {
    igx-select-item.select__entry {
        display: flex;
        align-items: center;
        justify-content: space-between;

        span {
            display: flex;
            padding: 8px;
            justify-content: space-between;
            width: 100%;
        }
    }
```
Where the inner span is actually `span.igx-drop-down__inner` - not something explicitly intended for users to style.
