### ISSUE TITLE
Themes: Allow changing the base font-size of the typography

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-angular#13376]

**Comment by Glopter** [comment]
Is this still being considered? The problem gets bigger with every new style that is ported from px to rem.

**Comment by simeonoff** [comment]
> Is this still being considered? The problem gets bigger with every new style that is ported from px to rem.

The issue will be addressed this/next week and will be available in a 16.1.x patch after it is merged.

**Comment by Glopter** [comment]
Great! Thank you for your quick response.

**Comment by simeonoff** [comment]
@Glopter 

I've introduced experimental changes to our theming library that allow you to configure the base font-size for all Ignite UI for Angular components. In the next patch of 16.1.x, you will be able to configure how how rem is calculated in the following way:

```scss
// Configure the base font-size
@use 'igniteui-theming/sass/config' as * with (
  $base-font-size: 10px // <-- 10px == 1rem
);

// Standard imports and theme declarations
@use 'igniteui-angular/src/lib/core/styles/themes' as *;

// This change also adds a new CSS variable `--ig-base-font-size`, which you can use to configure your own stylesheets:
html {
  font-size: var(--ig-base-font-size); // 10px
}

@include core();
@include typography();
@include theme();
```
