### ISSUE TITLE
IgxIcon: --size not working with em

### ISSUE THREAD

**Issue by Timmeeeey** [IgniteUI/igniteui-angular#13394]
## Description  
When `--igx-icon-size` is set to a value with a `em` unit then the icon size is too big.
I would like to use `em` because the icon size should be relative to the font-size of my text.

 * igniteui-angular version: 16.0.17
 * browser: any

## Steps to reproduce  

1. Set `--igx-icon-size: 2em;`

## Result
font-size: 16px;
```css
.igx-icon {
  font-size: 2em;  /* 32px ok */
  width: 2em;  /* 64px too big because 2em is now relative to the font-size above. This should be 1em. */
  height: 2em; /* same as width */
}
```

## Expected result  
When using following css it works because `width` and `height` are now always the same as `font-size`.
```css
.igx-icon {
  font-size: var(--size);
  width: 1em;
  height: 1em;
}
```

**Comment by simeonoff** [comment]
I don't even see how we can fix this. I'm not aware of any heuristic we can use to determine the unit in CSS and based on that to implement some logic that can convert the `width` and `height` values automatically when `--size` is expressed in `em`. 

The `--size` variable is there to spare people writing some extra lines for `width`, `height`, and `font-size`, which works great for units like `px`, `rem`, `cm`, etc. In your particular use case, however, some more work will be needed. For me the only viable solution is for you to write your styles like so:

```css
.igx-icon {
  --size: 1em; /* sets width and height */
  font-size: 2em; /* overwrite font-size so it doesn't read the --size variable */
}
```

**Comment by Timmeeeey** [comment]
Would following css not fix the problem?
`width` and `height` are then always the same size as `font-size` just like now.

```css
.igx-icon {
  width: 1em;
  height: 1em;
}
```
