### ISSUE TITLE
Multiple themes (light/dark)

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#1384]
### Description  
A question regarding themes:

In our application, users can choose between a light and dark theme. How do you go about doing this for igx? The themes documentations states "So we have themes for each component, and **a** global one, that styles the entire application and every component in it". Does this mean that we can only have a single global theme?

**Comment by simeonoff** [comment]
You can have component themes. Some components, like the checkbox or the input group have a property on their Sass theme function called $variant. The default variant is set to 'dark', but can also be set to 'light'.

For instance, to create a checkbox theme, that will lay against dark backgrounds, you can do:

```scss
// define your checkbox theme somewhere
$dark-cbx-theme: igx-checkbox-theme($variant: 'light', fill-color: #fff);

// If you want target support for post-IE11 browsers that have css variables support
// pass the theme you defined to the igx-css-vars mixin
:root { // make sure to scope the mixin as it spews out css variables
  @include igx-css-vars($dark-cbx-theme);
}

// OR

// If you want to support for IE11 you have to use the component styles
// mixin and pass the theme to that
@include igx-checkbox($dark-cbx-theme);
```

In both cases, be mindful of how View Encapsulation works in Angular.

Let me know if you have any questions.
