### ISSUE TITLE
Refactor: Card and List Components should set Avatar size to small by default

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-angular#14710]
Similar to what we've done in the Navbar, the Avatar component should be set to small size in the context of the Card and List components.

Take note that users should still be able to set a size for the avatar in the context of those components if they specified it in their own stylesheets:

```css
igx-card igx-avatar {
  --ig-size: var(--ig-size-medium);
}
```

The code above should still set the size of the avatar to medium in the context of the card after the change is implemented.
