### ISSUE TITLE
How do you change the text color inside combo box (placeholder color) ?

### ISSUE THREAD

**Issue by corganfuzz** [IgniteUI/igniteui-angular#3813]
I can change the background color of a combo box, but cannot change its text placeholder  ( see picture)

Looked in styles, but couldn't find it. I tried ng deep but it looks like is very very deep in!

![place](https://user-images.githubusercontent.com/11259414/52170955-9e005b80-2719-11e9-8566-1752a99d0b35.PNG)

**Comment by simeonoff** [comment]
@corganfuzz I have prepared a little [stackblitz sample](https://stackblitz.com/edit/angular-wjr32b?file=src%2Fapp%2Fcombo-main%2Fcombo-main.component.scss) for you that demonstrates how to theme the igx-input-group and icon-button used in the combo.

Try to strain from using the class/tag selectors of the components to style the components directly. Instead use the theme mixins(Sass) / CSS vars to style the components in your app.

**Comment by corganfuzz** [comment]
I need to learn how to work with these themes. any link you can provide for that?

Also, after a lot of trial and error this is what I did to make it work:

```css
::ng-deep {
  .igx-combo ::placeholder {
    color: white;
  }
}

```

and for the arrow's color:

```css
::ng-deep {
  .igx-combo .igx-input-group .igx-icon {
    color: white;
  }
}
```
