### ISSUE TITLE
Hide dialog header when empty

### ISSUE THREAD

**Issue by Eralmidia** [IgniteUI/igniteui-angular#546]
### Description  
Would it be possible to use an ngIf on the header, so it dosen't take up space if not assigned? We currently have our own setup for title for each screen (see image), but we now get a lot of white space on the top because of the empty dialog title

### Attachments  
![image](https://user-images.githubusercontent.com/12936286/35851500-848d5a76-0b28-11e8-8b77-28a2c12e196a.png)

**Comment by zdrawku** [comment]
If `title` is not set we intentionally leave this space blank because it is important not to change the alignment of the dialog elements, it looks more consistent and structured.

My suggestion is to use a custom CSS in order to fulfill your needs. Because of the Encapsulation limitatations of our style base you cannot apply a custom style just like that, although if you disable it you can remove the `paddings` and the title section wont take this space.

I have created a [sample ](https://stackblitz.com/edit/angular-v8zqet) for you that is showing the approach from above.

```css
.my-class .igx-dialog__window-title {
    padding-top: 0;
    padding-bottom: 0;
}

...

import { Component, Directive, HostBinding, HostListener, Input, ViewChildren, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'my-app',
  templateUrl: './app.component.html',
  styleUrls: [ './app.component.css' ],
  encapsulation: ViewEncapsulation.None
})
```

My general recomendation is to wait for the official theming release, once we are ready with it you will have the full power to customize your styles.
