### ISSUE TITLE
Be able to apply styling to a specific list item

### ISSUE THREAD

**Issue by jackofdiamond5** [IgniteUI/igniteui-angular#5504]
## Is your feature request related to a problem? Please describe.
I can't add background styling to a single list item in a straightforward manner.

## Describe the solution you'd like
I want to be able to do something along the lines of:
```css
.myListItem {
     background: blue;
}
```
