### ISSUE TITLE
Grid does not correct column width for the row selector column and header

### ISSUE THREAD

**Issue by jackofdiamond5** [IgniteUI/igniteui-angular#5559]
## Description  
If you make it so the containers of the grid's header  and row selector icons have different widths, the grid fails to correct them and as a consequence, they appear misaligned.

 * igniteui-angular version: 7.3.x, 8.1.x
 * browser: n/a

## Steps to reproduce  

1. Open the `/gridSelection` dev sample.
2. In the `grid-selection.sample.css` file enter:
```css
::ng-deep div.igx-grid__cbx-selection {
 width: 200px;
}
 
::ng-deep .igx-grid__thead div.igx-grid__cbx-selection {
 width: 100px;
}
```
3. Build and run.
4. Observe.

## Result  
The column responsible for row selection is misaligned.

## Expected result  
There should be no misaligned columns.

## Attachments  

![Annotation 2019-07-31 163225](https://user-images.githubusercontent.com/16020256/62216087-ce674080-b3b0-11e9-9739-bdf39b8262b4.png)
