### ISSUE TITLE
Grid Toolbar button color is changed to #e41c77

### ISSUE THREAD

**Issue by jaya0selva** [IgniteUI/igniteui-angular#6174]
## Description  
Default Toolbar button color is changed

 * igniteui-angular version: 8.2.8
 * browser: Chrome

## Steps to reproduce  
https://stackblitz.com/edit/angular-tozup8

## Result  
color: #e41c77;

## Expected result  
Default color should be color: rgba(0,0,0,.54);

## Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/40403770/69047415-13c38280-0a21-11ea-9085-29155d0cf8ef.png)

**Comment by simeonoff** [comment]
Hello @jaya0selva, we recently changed the design of the buttons in the toolbar to the default one because of #4958 related to disabled button styles in the toolbar. 

You can still use themes with to alter the button look and feel in the toolbar if you prefer the text to be gray, instead of the default orange.

Here's an example of how this can be done:
```scss
igx-grid-toolbar {
    @include igx-button(
        igx-button-theme(
            $outlined-text-color: igx-color($default-palette, 'grays', 600)
        )
    );
}
```
