### ISSUE TITLE
Cannot use gradient for progress bar color

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#6245]
## Description  
I'm trying to apply a linear gradient for the circular progress bar color, but I'm unable to.

 * igniteui-angular version: 8.2.10
 * browser: All

## Steps to reproduce  

1. Define a circular progress bar
2. Apply linear gradient color to it.
```css
.stats-progress {
  width: auto;
  height: auto;
  --igx-circular-bar-progress-circle-color: linear-gradient(to right, $progress-success, $secondary);
}
```

## Result  
There is no progress fill color.

## Expected result  
The linear gradient is applied to the progress fill color.

**Comment by simeonoff** [comment]
@kdinev The reason linear gradient is not working is because the stroke property, which we use to color the underlying SVG element, doesn't work with the linear-gradient function in CSS. Gradients in SVG documents are added quite differently. 

We can still provide some very specific way of defining a start and end a stop color in Sass for your gradient, but it will not be as flexible as linear-gradient - you will be limited to two colors only, and the direction will be predefined.

There's an alternative approach where we allow you to project your own SVG gradient using Angular templates. Then after flipping a switch in the circular progress theme, your gradient will start working.

Tell me what you think and in which direction would you rather like us to take this request in?

**Comment by kdinev** [comment]
@simeonoff I would prefer whichever option is more flexible. The second one sounds like covering more scenarios than the first. Can you give me an example of what that would look like in code setup?

**Comment by simeonoff** [comment]
The second option will require you to do something like:

```html
<!-- Define a gradient template -->
<igx-circular-bar value="86">
    <ng-template igxSvgGradient>
        <linearGradient id="linear" x1="0%" y1="0%" x2="100%" y2="0%">
            <stop offset="0%"   stop-color="#05a"/>
            <stop offset="100%" stop-color="#0a5"/>
        </linearGradient>
    </ng-template>
</igx-circular-bar>
```

You can then use your gradient reference in your linear-gradient theme:

```scss
$circular-theme: igx-progress-circular-theme(
    $progress-circle-color: url(#linear)
);

@include igx-progress-circular($circular-theme);
```

**Comment by kdinev** [comment]
@simeonoff And what would the first option look like? Three inputs for start, end and angle?

**Comment by simeonoff** [comment]
It will look something like:

```scss
$circular-theme: igx-progress-circular-theme(
    $progress-circle-color-start: red,
    $progress-circle-color-end: blue
);

.fancy-progress {
    @include igx-progress-circular($circular-theme);
}
```

Of course, the limitations are obvious, you can only specify a pre-defined amount of colors, and the angle would either need to be set in advance, or another property must be exposed to control that.
