### ISSUE TITLE
Change fonts used in IgxGridComponent column Header text

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#6470]
## Question  
How do I change the font-size, font-style, and font color of each column header text

 * igniteui-angular version: 8.2.15
 * browser: Google Chrome

**Comment by ChronosSF** [comment]
Hey,

The grid theming allows for changing the header text color but not the font-size/family so you'll have to override the appropriate classes instead.

Something like this should work for both grids:

```scss
$custom-igx-grid-theme: igx-grid-theme(
  $header-text-color: red
);

.igx-grid__th-title {
  font-family: Verdana;
  font-size: 1.25rem;
}

@include igx-grid($custom-igx-grid-theme);
```

You can also check the following stackblitz - https://stackblitz.com/edit/angular-aawzea?file=src%2Fapp%2Ftree-grid-paging-sample%2Ftree-grid-paging-sample.component.scss
