### ISSUE TITLE
Change font size of IgxTreeGridComponent Header Text

### ISSUE THREAD

**Issue by brookhutchinson** [IgniteUI/igniteui-angular#6944]
## Question  
How do I change the font size of the text that displays inside the `TreeGridComponent` Header

 * igniteui-angular version: 8.2.18
 * browser: Google Chrome Version 80.0.3987.132 (Official Build) (64-bit)

I have the following SCSS defined to style my `TreeGridComponent`. What SCSS should I add?

```scss
@import './../../../../../theme';

$treegrid-theme: igx-grid-theme(
  $expand-icon-color: #000,
  $expand-icon-hover-color: #000,
  $header-background: #F5F5F5,
  $header-text-color: #000
);

:host {
  ::ng-deep {
    @include igx-grid($treegrid-theme);
  }
}
```
