### ISSUE TITLE
Themes: Include input auto-fill styles for Chromium-based browsers.

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-angular#7786]
In Chrome and the new Edge, there's a weird user-agent style applied. It looks like this:

![image](https://user-images.githubusercontent.com/1472513/86748300-06f1ae80-c045-11ea-8e56-a036e05938b1.png)

The user agent style is this:
```css
input:-internal-autofill-selected {
    -webkit-appearance: menulist-button;
    background-color: rgb(232, 240, 254) !important;
    background-image: none !important;
    color: -internal-light-dark-color(black, white) !important;
}
```

I hope we can get an override for this in our theme.
Here's my form:
```html
<form class="login-buttons" #userLogin="ngForm" (ngSubmit)="loginWithForm()">
  <igx-input-group class="login-button" type="border">
    <label for="username" igxLabel>Username</label>
    <igx-prefix>
      <igx-icon>person</igx-icon>
    </igx-prefix>
    <input #userName igxInput id="username" required name="username" [(ngModel)]="logininfo.username" />
  </igx-input-group>

  <igx-input-group class="login-button" type="border">
    <label for="passwordField" igxLabel>Password</label>
    <input #passwordField igxInput type="password" required id="passwordField" name="passwordField" [(ngModel)]="logininfo.password" />
  </igx-input-group>

  <igx-checkbox name="rememberme" [(ngModel)]="logininfo.rememberMe">
    Remember me
  </igx-checkbox>

  <button igxButton="outlined"
          class="submit-button space-out"
          [disabled]="!userLogin.touched || !userLogin.valueChanges || userLogin.invalid || submitInProgress">
    Login
  </button>
</form>
```

_Originally posted by @kdinev in https://github.com/IgniteUI/igniteui-angular/issues/6839#issuecomment-654689415_

**Comment by kdinev** [comment]
Thanks for moving this @simeonoff!

**Comment by simeonoff** [comment]
@kdinev sure, np :)

**Comment by simeonoff** [comment]
@kdinev We already apply a [hack for that issue](https://github.com/IgniteUI/igniteui-angular/blob/f125387ded189060bb42a42e89d5bdc61a370087/projects/igniteui-angular/src/lib/core/styles/components/input/_input-group-theme.scss#L1003). There must be something going on in your app that overrides the `transition-delay` we apply, thus why you see the browser styles.

However, after further investigation, we still found an issue with the autocomplete styles in the bootstrap input theme, for which we will provide a PR and reference this issue.

**Comment by kdinev** [comment]
@didimmova @simeonoff I did some further digging up and discovered the autofill issue still appears in the cases when the form is in an `igx-dialog`. I suppose there's some conflict with the dialog animation on show, or with the form being hidden initially, that still makes the autofill styles by the browser be applied.

I was able to resolve it on an application level like this:

```css
.igx-input-group__input {
  border-top-color: #192053;
}

input:-webkit-autofill,
input:-webkit-autofill:hover,
input:-webkit-autofill:focus,
input:-webkit-autofill:active  {
  -webkit-box-shadow: 0 0 0 40px #192053 inset !important;
}

input:-webkit-autofill {
  -webkit-text-fill-color: white !important;
}
```

Unless there's something you can do to resolve the conflict between your fix and the dialog, the workaround on an application level is good enough!
