### ISSUE TITLE
IgxGrid - Row Selection Background color should be !Important

### ISSUE THREAD

**Issue by Swiftpaws** [IgniteUI/igniteui-angular#7979]
## Description  
Using conditional cell styling hides row selection color.
Row backgrounds are colorized in multiple colors 

 * igniteui-angular version: 10.0.1
 * browser: Newest Chrome

## Steps to reproduce  

1. Setup conditional cell styling with background-color modifications (one row blue the other one red and so on)
2.  Set row selection to multiple and cell selection to none
3. Select a row which has a conditional cell class applied to it

## Result  
Only the selection border is visible, but the background is not changed to $row-selected-background

## Expected result  
Row selection should override applied cell styles (set !important for $row-selected-background)

## Attachments  

Working around this issue: Not very clean, but works

```scss
$text-color: black;
$background-color: #f2c43c;

$custom-grid-theme: igx-grid-theme(
  $row-selected-text-color: $text-color,
  $row-selected-background: $background-color,
  $row-selected-hover-background: $background-color,

  $cell-active-border-color: transparent,
);
```

```scss
:host {
  ::ng-deep {
    @include igx-grid($custom-grid-theme);

    .class1{
      background-color: lightblue;
    }

    .class2{
      background-color: lightgreen;
    }
    .igx-grid__tr--selected {
      .class1{
        background-color: transparent;
      }

      .class2{
        background-color: transparent;
      }
    }
  }
}
````
