### ISSUE TITLE
Themes: extended palette variants should be based on the 500 variant

### ISSUE THREAD

**Issue by simeonoff** [IgniteUI/igniteui-angular#9119]
## Is your feature request related to a problem? Please describe.
The palette variants exposed as CSS variables should be based on the 500 variant so they can be modified at runtime without the need to change every single color variant separately.

With the upcoming changes to the theming in 12.0.0, users will be able to modify palette colors using CSS variables:

```css
:root {
  --igx-primary-500: orange;
}
```

This will work but it will not automatically update all other variants of the primary color. Users will need to change each one individually.

## Describe the solution you'd like
We should try to come up with a CSS compatible solution that generates color variants from the base 500 variants for the primary, secondary, and grays palette at run-time. We can enforce setting the primary color as HSL values so that we can recalculate them;

For instance, `#09f` (Infragistics blue) can be represented like so:

```css
:root {
  --igx-primary-h: 204;
  --igx-primary-s: 100%;
  --igx-primary-l: 50%;

  /* later */
  --igx-primary-500: hsl(var(--igx-primary-h), var(--igx-primary-s), var(--igx-primary-l));

  /* the 600 variant of the primary color generated using calc */
  --igx-primary-600: hsl(var(--igx-primary-h), var(--igx-primary-s), calc(var(--igx-primary-l) * .9));
}
```
This requires a paradigm shift in how our users will define their main `primary`, `secondary` and so on colors, but it allows for a much more flexible and run-time possible modification of the entire color palette.
