### ISSUE TITLE
igx-avatar custom theme overrides the avatar shape and makes it square

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular#9446]
## Description  
When I define custom scoped theme for a round shaped avatar, the avatar becomes square.

 * igniteui-angular version: 12.0.x
 * browser: all

## Steps to reproduce  

1. Define a round shaped avatar and scope a theme with custom color for the avatar
```html
<igx-avatar class="empty-role"
            icon="add"
            [roundShape]="true"
	    size="large">
</igx-avatar>
```

```scss
@import "~@infragistics/igniteui-angular/lib/core/styles/themes/index";
@import "~minireset.css/minireset";
@include igx-core();

@include igx-typography(
  $font-family: "'Poppins', sans-serif"
);

$include: (igx-avatar);

@include igx-dark-theme(
  $palette: $app-palette,
  $exclude: map-keys(map-remove($components, $include...),)
);

.empty-role {
  $empty-role-avatar: igx-avatar-theme($color: #000, $size: 88px);
  @include igx-css-vars($empty-role-avatar);
}
```

## Result  
The avatar is square shaped.

## Expected result  
The avatar should be round shaped. I also notice that in the output theme from the mixin, the avatar uses css vars that no longer exist.

## Attachments  
![image](https://user-images.githubusercontent.com/1472513/116233344-d4e04300-a763-11eb-9fa6-b887b9a761de.png)
